language: c
sudo: true
cache:
   directories:
   - ~/arduino_ide
   - ~/.arduino15/packages/
git:
   depth: false
   quiet: true
env:
   global:
   - PRETTYNAME="BlueDisplay"
   - INSTALL_PLATFORMS="avr,STM32"
before_install:
- source <(curl -SLs https://raw.githubusercontent.com/ArminJo/travis-ci-arduino/master/install.sh)
# enable all compilation warnings
#- arduino --pref "compiler.warning_level=all" --save-prefs
script:
- build_platform BluePill
- build_platform uno
- build_platform leonardo
- build_platform cplayClassic
notifications:
   email:
      recipients:
      - armin.arduino@gmail.com
      on_success: change
      on_failure: always